=== noranorab/Openflexo-Proj/OtawaCache.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   elementFormDefault="qualified"
		   xmlns="http://mem4csd.telecom-paris.fr/OtawaCache"
           targetNamespace="http://mem4csd.telecom-paris.fr/OtawaCache">
  <xs:element name="block_bits" type="xs:byte"/>
  <xs:element name="way_bits"   type="xs:byte"/>
  <xs:element name="row_bits"   type="xs:byte"/>
  <xs:element name="miss_penalty" type="xs:byte"/>
  <xs:element name="dcache">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="block_bits"/>
        <xs:element ref="way_bits"/>
        <xs:element ref="row_bits"/>
        <xs:element ref="miss_penalty"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="icache">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="block_bits"/>
        <xs:element ref="way_bits"/>
        <xs:element ref="row_bits"/>
        <xs:element ref="miss_penalty"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="CACHECONFIG">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dcache"/>
        <xs:element ref="icache"/>
      </xs:sequence>
	  <xs:attribute type="xs:string" name="class"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== noranorab/Openflexo-Proj/otawa_cache.xml
<?xml version="1.0" encoding="UTF-8"?>
<CACHECONFIG
  xmlns="http://mem4csd.telecom-paris.fr/OtawaCache"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://mem4csd.telecom-paris.fr/OtawaCache OtawaCache.xsd">
  <dcache>
    <block_bits>5</block_bits>
    <way_bits>2</way_bits>
    <row_bits>9</row_bits>
    <miss_penalty>25</miss_penalty>
  </dcache>
  <icache>
    <block_bits>5</block_bits>
    <way_bits>2</way_bits>
    <row_bits>9</row_bits>
    <miss_penalty>25</miss_penalty>
  </icache>
</CACHECONFIG>
