=== noranorab/Openflexo-Proj/OtawaMemory.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://mem4csd.telecom-paris.fr/OtawaMemory" 
		xmlns="http://mem4csd.telecom-paris.fr/OtawaMemory"
		elementFormDefault="qualified">
  <xs:element name="offset" type="xs:string"/>
  <xs:element name="name" type="xs:string"/>
  <xs:element name="address">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="offset"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="size" type="xs:string"/>
  <xs:element name="type" type="xs:string"/>
  <xs:element name="latency" type="xs:byte"/>
  <xs:element name="writable" type="xs:boolean"/>
  <xs:element name="cachable" type="xs:boolean"/>
  <xs:element name="bank">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="address"/>
        <xs:element ref="size"/>
        <xs:element ref="type"/>
        <xs:element ref="latency"/>
        <xs:element ref="writable"/>
        <xs:element ref="cachable"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="banks">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="bank" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="memory">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="banks"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== noranorab/Openflexo-Proj/otawa_memory.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<memory
	xmlns="http://mem4csd.telecom-paris.fr/OtawaMemory"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://mem4csd.telecom-paris.fr/OtawaMemory OtawaMemory.xsd">
	<banks>
		<bank>
			<name>RAM</name>
			<address><offset>0x00000000</offset></address>
			<size>0x1fffffff</size>
			<type>DRAM</type>
			<latency>25</latency>
			<writable>true</writable>
			<cachable>true</cachable>
		</bank>
	</banks>
</memory>
